### ISSUE TITLE
Alpine Holland Docker Image

### ISSUE THREAD

**Issue by kzap** [holland-backup/holland#245]
Hi,

I made a Docker Alpine Image with all the various Holland Backup plugins and database exports clients:
https://hub.docker.com/r/sylabsio/cloud-services/
https://github.com/sylabs/services-base-images/tree/docker/holland-backup-alpine

- Docker

	```sh
	docker run -d \
	  -v `pwd`/holland-data/config:/etc/holland \
	  -v `pwd`/holland-data/backups:/var/spool/holland \
	  sylabsio/cloud-services:holland-backup-alpine
	```

- Docker Compose

	```yaml
	version: '3'

	services:
	  holland:
	    image: sylabsio/cloud-services:holland-backup-alpine
	    volumes:
	      - ./holland-data/config:/etc/holland
	      - ./holland-data/backups:/var/spool/holland
	```

Using it at the moment to run backups via Docker containers, may not work in all cases but still hope it helps
